version: '3.8'

services:
  openresty:
    container_name: openresty
    image: openresty/openresty:alpine-fat
    volumes:
      - /home/unknown/Code/openresty/nginx:/etc/nginx/conf.d
      - /home/unknown/Code/openresty/templates/:/templates
      - /home/unknown/Code/openresty/lualib:/usr/local/openresty/site/lualib
    ports:
      - 8080:80
      - 7000:7000
    depends_on:
      - tarantool

  tarantool:
    container_name: tarantool
    image: tarantool/tarantool
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=password
    volumes:
      - /home/unknown/Code/openresty/tarantool:/var/lib/tarantool
    ports:
      - 3301:3301